module.exports.cariRoute = require('./cari.route')
module.exports.temsilciRoute = require('./temsilci.route')
module.exports.depoRoute = require('./depo.route')
module.exports.siparisRoute = require('./siparis.route')
module.exports.odemePlanRoute = require('./odeme_plan.route')
