module.exports.Cari = require('./cari.service')
module.exports.Stok = require('./stok.service')
module.exports.Temsilci = require('./temsilci.service')
module.exports.CariHareket = require('./cari_hareket.service')
module.exports.Depo = require('./depo.service')
module.exports.Siparis = require('./siparis.service')
module.exports.OdemePlan = require('./odeme_plan.service')
