module.exports.Siparis = require('./siparis.validation')
module.exports.Stok = require('./stok.validation')
module.exports.Satis = require('./satis.validation')
module.exports.Aykur = require('./aykur.validation')
module.exports.Maliyet = require('./maliyet.validation')
module.exports.Kampanya = require('./kampanya.validation')
module.exports.Tahsilat = require('./tahsilat.validation')
module.exports.FiyatListe = require('./fiyat_liste.validation')
