module.exports.Cari = require('./cari.controller')
module.exports.Stok = require('./stok.controller')
module.exports.Temsilci = require('./temsilci.controller')
module.exports.Depo = require('./depo.controller')
module.exports.Siparis = require('./siparis.controller')
module.exports.OdemePlan = require('./odeme_plan.controller')
