module.exports.Cari = require('./cari.model')
module.exports.Temsilci = require('./temsilci.model')
module.exports.CariHareket = require('./cari_hareket.model')
module.exports.Depo = require('./depo.model')
module.exports.Siparis = require('./siparis.model')
module.exports.OdemePlan = require('./odeme_plan.model')
